/**
 * The Ancient Seas Trilogy title page (/ancientseas/): everything about it that is data.
 *
 * Pure — no DOM, no React, no era content — so `npm run ancientseas` can check it headless: that
 * the version parameter defaults sensibly, that every game links to an entry page that exists and
 * shows a title image that exists, that every image version 2 asks for has a brief open in
 * docs/image-requests.md, and that the page never asks the network for a requested file that has
 * not been delivered (`delivered.json`, regenerated by `npm run ancientseas:delivered`).
 *
 * Two versions, picked by `?version=`:
 *   1 — the three games' own title paintings, whole, on a dark ground shaped to their vignettes.
 *   2 — one composition in the paintings' own style, assembled from individually requested
 *       pieces: an engraved trilogy title, engraved game titles, and the animals and plants
 *       arranged round them. Until a piece is delivered its slot draws a stand-in.
 */
import DELIVERED from './delivered.json';

export type PageVersion = 1 | 2;
export const DEFAULT_VERSION: PageVersion = 1;
export const VERSIONS: readonly PageVersion[] = [1, 2];

/** `?version=2` → 2; anything else, including nothing, is the default. */
export function parseVersion(search: string): PageVersion {
  const raw = new URLSearchParams(search).get('version');
  return raw !== null && VERSIONS.includes(Number(raw) as PageVersion) ? (Number(raw) as PageVersion) : DEFAULT_VERSION;
}

export type EraId = 'cambrian' | 'devonian' | 'triassic';

export interface GameLink {
  readonly id: EraId;
  readonly title: string;
  /** Entry page, relative to the app root (the trilogy page lives one level below it). */
  readonly path: string;
  /** The game's own composed title painting, the one its title screen shows. */
  readonly art: string;
  readonly artWidth: number;
  readonly artHeight: number;
  /** The engraved wordmark cut from that painting, on transparency. */
  readonly wordmark: string;
  /** Period, as the game's own copy puts it (`copy.taglineEm`); the test keeps these in step. */
  readonly when: string;
  readonly tagline: string;
}

export const GAMES: readonly GameLink[] = [
  {
    id: 'cambrian', title: 'Cambrian Conquest', path: '',
    art: 'assets/brand/logo-illustrated.webp', artWidth: 1536, artHeight: 1024,
    wordmark: 'assets/brand/logo-engraved.webp',
    when: '508 million years ago', tagline: 'Eat. Grow. Fight. Run.',
  },
  {
    id: 'devonian', title: 'Devonian Domination', path: 'devonian/',
    art: 'assets/devonian/brand/title.webp', artWidth: 1536, artHeight: 1024,
    wordmark: 'assets/devonian/brand/logo-engraved.webp',
    when: '375 million years ago', tagline: 'Feed. Grow. Fight. Escape.',
  },
  {
    id: 'triassic', title: 'Triassic Triumph', path: 'triassic/',
    art: 'assets/triassic/brand/title.webp', artWidth: 1536, artHeight: 1024,
    wordmark: 'assets/triassic/brand/logo-engraved.webp',
    when: '240 million years ago', tagline: 'Breathe. Dive. Hunt. Surface.',
  },
];

/** Where every piece the trilogy page asks for lives once delivered. */
export const ART_DIR = 'assets/ancientseas/';

/**
 * The trilogy wordmark for version 1: engraved lettering with the gold rim the three game
 * wordmarks carry, on transparency, for a dark ground. Typeset until it lands.
 */
export const TRILOGY_LOGO = `${ART_DIR}logo-engraved.webp`;

/** A piece of the version-2 composition and where it sits. */
export interface Placement {
  /** Centre, as a percentage of the stage's width and height. */
  readonly x: number;
  readonly y: number;
  /** Width as a percentage of the stage's width; height follows the piece's aspect. */
  readonly w: number;
  /** Degrees, clockwise. */
  readonly rot?: number;
  readonly flip?: boolean;
}

export type SlotKind = 'title' | 'animal' | 'plant' | 'ornament' | 'ground';

export interface Slot {
  readonly id: string;
  readonly kind: SlotKind;
  /** What the picture is of — the placeholder's label and the brief's subject. */
  readonly label: string;
  /** Requested file, under `ART_DIR`. */
  readonly file: string;
  /** Requested pixel size; the placeholder keeps the same aspect so the arrangement reads. */
  readonly width: number;
  readonly height: number;
  /** Something already shipped that can hold the place until the request is delivered. */
  readonly standIn?: string;
  /** For a title: the game it opens. */
  readonly game?: EraId;
  readonly z: number;
  readonly desktop: Placement;
  readonly mobile: Placement;
}

/** Stage proportions, height over width; the CSS aspect-ratio and the overlap test both read these. */
export const STAGE = { desktop: 10 / 16, mobile: 25 / 9 } as const;

/**
 * The composition. The desktop stage is 16:10 and reads left to right as the paintings do — the
 * Cambrian's animals round the Cambrian's title, and so on — with the plants the three paintings
 * share filling between. The mobile stage is 9:25 and stacks the same three groups: each game's
 * big animal arching over its title, its three smaller animals in a row beneath.
 */
const A = (id: string, label: string, standIn: string | undefined, z: number, desktop: Placement, mobile: Placement, width = 1024, height = 768): Slot =>
  ({ id, kind: 'animal', label, file: `${ART_DIR}animal-${id}.webp`, width, height, standIn, z, desktop, mobile });
/** A second or third plant of a kind is the same drawing again, mirrored: `of` names the one whose file it shares. */
const P = (id: string, label: string, z: number, desktop: Placement, mobile: Placement, width = 768, height = 1024, of = id): Slot =>
  ({ id, kind: 'plant', label, file: `${ART_DIR}plant-${of}.webp`, width, height, z, desktop, mobile });

export const SLOTS: readonly Slot[] = [
  // ---- ground: the parchment itself, mottled and vignetted like the paintings' ----
  { id: 'parchment', kind: 'ground', label: 'Parchment ground', file: `${ART_DIR}ground-parchment.webp`, width: 2048, height: 1280, z: 0,
    desktop: { x: 50, y: 50, w: 100 }, mobile: { x: 50, y: 50, w: 100 } },
  { id: 'seabed', kind: 'ground', label: 'Seabed strip', file: `${ART_DIR}ground-seabed.webp`, width: 2048, height: 384, z: 1,
    desktop: { x: 50, y: 91, w: 100 }, mobile: { x: 50, y: 98.5, w: 140 } },

  // ---- titles ----
  { id: 'trilogy', kind: 'title', label: 'Ancient Seas Trilogy', file: `${ART_DIR}title-trilogy.webp`, width: 2048, height: 640, z: 30,
    desktop: { x: 50, y: 11, w: 46 }, mobile: { x: 50, y: 5.5, w: 88 } },
  { id: 'cambrian', kind: 'title', label: 'Cambrian Conquest', file: `${ART_DIR}title-cambrian.webp`, width: 1536, height: 640, z: 30,
    standIn: 'assets/brand/logo-engraved.webp', game: 'cambrian',
    desktop: { x: 18, y: 50, w: 26 }, mobile: { x: 50, y: 30.3, w: 74 } },
  { id: 'devonian', kind: 'title', label: 'Devonian Domination', file: `${ART_DIR}title-devonian.webp`, width: 1536, height: 640, z: 30,
    standIn: 'assets/devonian/brand/logo-engraved.webp', game: 'devonian',
    desktop: { x: 50, y: 50, w: 26 }, mobile: { x: 50, y: 57.8, w: 74 } },
  { id: 'triassic', kind: 'title', label: 'Triassic Triumph', file: `${ART_DIR}title-triassic.webp`, width: 1536, height: 640, z: 30,
    standIn: 'assets/triassic/brand/logo-engraved.webp', game: 'triassic',
    desktop: { x: 82, y: 50, w: 26 }, mobile: { x: 50, y: 85.3, w: 74 } },

  // ---- the shell fleuron the paintings put between title and animals ----
  { id: 'fleuron', kind: 'ornament', label: 'Scallop fleuron', file: `${ART_DIR}ornament-fleuron.webp`, width: 512, height: 384, z: 20,
    desktop: { x: 50, y: 24.5, w: 4.5 }, mobile: { x: 50, y: 12.3, w: 12 } },

  // ---- Cambrian, left ----
  A('anomalocaris', 'Anomalocaris', undefined, 25, { x: 17, y: 34, w: 26 }, { x: 48, y: 21, w: 56 }),
  A('opabinia', 'Opabinia', undefined, 24, { x: 32, y: 41, w: 11 }, { x: 50, y: 40, w: 26 }),
  A('trilobite', 'Olenoides', undefined, 26, { x: 7, y: 68, w: 13 }, { x: 20, y: 40, w: 26 }),
  A('hallucigenia', 'Hallucigenia', undefined, 26, { x: 27, y: 68, w: 14 }, { x: 80, y: 40, w: 26 }),

  // ---- Devonian, middle ----
  A('dunkleosteus', 'Dunkleosteus', 'assets/devonian/brand/emblem.webp', 25, { x: 48, y: 34, w: 25 }, { x: 48, y: 48.5, w: 56 }),
  A('cladoselache', 'Cladoselache', undefined, 24, { x: 63, y: 39, w: 12 }, { x: 50, y: 67.5, w: 26 }),
  A('ammonoid', 'Ammonoid', undefined, 26, { x: 39, y: 69, w: 12 }, { x: 20, y: 67.5, w: 26 }),
  A('bothriolepis', 'Bothriolepis', undefined, 26, { x: 59, y: 69, w: 13 }, { x: 80, y: 67.5, w: 26 }),

  // ---- Triassic, right ----
  A('cymbospondylus', 'Cymbospondylus', undefined, 25, { x: 82, y: 33, w: 28 }, { x: 48, y: 76, w: 56 }),
  A('mixosaurus', 'Mixosaurus', undefined, 24, { x: 93, y: 41, w: 11 }, { x: 50, y: 95, w: 26 }),
  A('nautiloid', 'Nautiloid', undefined, 26, { x: 71, y: 69, w: 12 }, { x: 20, y: 95, w: 26 }),
  A('placodont', 'Placodus', 'assets/triassic/brand/emblem.webp', 26, { x: 91, y: 69, w: 13 }, { x: 80, y: 95, w: 26 }),

  // ---- plants, shared by all three paintings ----
  P('crinoid', 'Crinoid', 10, { x: 3.5, y: 44, w: 7 }, { x: 5, y: 33, w: 12 }),
  P('crinoid-b', 'Crinoid', 10, { x: 96.5, y: 44, w: 7, flip: true }, { x: 95, y: 60, w: 12, flip: true }, 768, 1024, 'crinoid'),
  P('sea-fern', 'Sea fern', 5, { x: 18, y: 50, w: 22 }, { x: 50, y: 30.3, w: 60 }, 1024, 768),
  P('sea-fern-b', 'Sea fern', 5, { x: 50, y: 50, w: 22, flip: true }, { x: 50, y: 57.8, w: 60, flip: true }, 1024, 768, 'sea-fern'),
  P('sea-fern-c', 'Sea fern', 5, { x: 82, y: 50, w: 22 }, { x: 50, y: 85.3, w: 60 }, 1024, 768, 'sea-fern'),
  P('red-coral', 'Red branching coral', 12, { x: 13, y: 83, w: 9 }, { x: 5, y: 97.5, w: 12 }),
  P('red-coral-b', 'Red branching coral', 12, { x: 87, y: 83, w: 9, flip: true }, { x: 95, y: 97.5, w: 12, flip: true }, 768, 1024, 'red-coral'),
  P('tube-sponge', 'Tube sponges', 12, { x: 33, y: 84, w: 7 }, { x: 36, y: 98.5, w: 11 }),
  P('tube-sponge-b', 'Tube sponges', 12, { x: 67, y: 84, w: 7, flip: true }, { x: 64, y: 98.5, w: 11, flip: true }, 768, 1024, 'tube-sponge'),
  P('brain-coral', 'Brain coral', 11, { x: 50, y: 85, w: 8 }, { x: 50, y: 99, w: 14 }, 1024, 768),
];

/** Every file the page asks for: the version-1 wordmark and each version-2 drawing once, however many slots share it. */
export const REQUESTED: readonly string[] = [...new Set([TRILOGY_LOGO, ...SLOTS.map((s) => s.file)])];

const delivered = new Set<string>(DELIVERED.files);
/** True once the file has been dropped into public/ and `npm run ancientseas:delivered` has seen it. */
export const isDelivered = (file: string) => delivered.has(file);

/** What a slot actually draws: the delivered request, a shipped stand-in, or a placeholder. */
export type SlotSource = { kind: 'delivered'; src: string } | { kind: 'stand-in'; src: string } | { kind: 'placeholder' };
export function sourceFor(slot: Slot): SlotSource {
  if (isDelivered(slot.file)) return { kind: 'delivered', src: slot.file };
  if (slot.standIn) return { kind: 'stand-in', src: slot.standIn };
  return { kind: 'placeholder' };
}
