/** Actual Three.js GLB playback review, isolated from the repository viewer. */
import {createHash} from 'node:crypto';import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import{chromium}from'playwright-core';
const root=path.resolve(import.meta.dirname,'../../../..'),local=path.resolve(root,'../devonian-authoring/coccosteus'),candidate=path.join(local,'v2-candidate');
const sourceGlbSha256=createHash('sha256').update(await fs.readFile(path.join(candidate,'coccosteus.glb'))).digest('hex');
const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0;background:#142027;color:#e4e8de;font:18px system-ui}#label{position:absolute;top:20px;left:25px}canvas{display:block}</style><script type="importmap">{"imports":{"three":"/modules/build/three.module.js","three/addons/":"/modules/examples/jsm/"}}</script></head><body><div id="label">Loading Coccosteus V2</div><script type="module">
import * as T from 'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
const scene=new T.Scene();scene.background=new T.Color(0x142027);const renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(1100,800);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;document.body.appendChild(renderer.domElement);const camera=new T.PerspectiveCamera(35,1100/800,.01,100);camera.position.set(4,2.8,5.2);camera.lookAt(0,.04,-.4);scene.add(new T.HemisphereLight(0xdbe8ed,0x514332,2));const key=new T.DirectionalLight(0xfff2dc,3);key.position.set(3,6,5);scene.add(key);const fill=new T.DirectionalLight(0xb8d4ee,1.5);fill.position.set(-4,2,-3);scene.add(fill);
const gltf=await new GLTFLoader().loadAsync('/coccosteus.glb');scene.add(gltf.scene);const mixer=new T.AnimationMixer(gltf.scene);let clock=new T.Clock();let active;window.ready=true;window.clips=gltf.animations.map(c=>({name:c.name,duration:c.duration}));window.setClip=name=>{mixer.stopAllAction();const clip=T.AnimationClip.findByName(gltf.animations,name);active=mixer.clipAction(clip);active.setLoop(T.LoopOnce,1);active.clampWhenFinished=true;active.reset().play();clock.getDelta();document.querySelector('#label').textContent='Coccosteus V2 · '+name;return clip.duration;};
window.audit=()=>{const result=[];for(const clip of gltf.animations){mixer.stopAllAction();const action=mixer.clipAction(clip);action.setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.reset().play();let finite=true,rootStable=true;const points=[];for(let i=0;i<=90;i++){mixer.setTime(clip.duration*i/90);gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(o=>{if(!o.matrixWorld.elements.every(Number.isFinite))finite=false;if(o.name==='root'&&(o.position.length()>1e-6||o.quaternion.angleTo(new T.Quaternion())>1e-5))rootStable=false;});const tip=gltf.scene.getObjectByName('caudal');points.push(tip.getWorldPosition(new T.Vector3()).toArray());}result.push({name:clip.name,duration:clip.duration,finite,rootStable,tailTipTravel:points.slice(1).reduce((n,p,i)=>n+new T.Vector3(...p).distanceTo(new T.Vector3(...points[i])),0)});}mixer.stopAllAction();return result;};
let recorder,chunks=[];window.startRecord=()=>{chunks=[];recorder=new MediaRecorder(renderer.domElement.captureStream(30),{mimeType:'video/webm'});recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();};window.stopRecord=()=>new Promise(resolve=>{recorder.onstop=async()=>resolve(Array.from(new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())));recorder.stop();});
renderer.setAnimationLoop(()=>{mixer.update(Math.min(clock.getDelta(),.05));renderer.render(scene,camera);});
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{let file;if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(req.url.startsWith('/modules/'))file=path.join(root,'node_modules/three',req.url.slice(9));else if(req.url==='/coccosteus.glb')file=path.join(candidate,'coccosteus.glb');else{res.statusCode=404;res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'model/gltf-binary');res.end(await fs.readFile(file));}catch(e){res.statusCode=500;res.end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1100,height:800}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+port);await page.waitForFunction(()=>window.ready);const audit=await page.evaluate(()=>window.audit());if(audit.some(r=>!r.finite||!r.rootStable))throw Error('Animation audit failed');await fs.writeFile(path.join(local,'playback-validation-v2.json'),JSON.stringify({sourceGlbSha256,audit,errors},null,2));
await page.evaluate(()=>window.startRecord());
for(const name of ['Idle','Swim','TurnLeft','TurnRight','Dive','Rise','Attack','Bite','Heavy','Hit','Guard','Parry','Dodge','Eat','Stagger','Ability','Growth','Death']){const duration=await page.evaluate(n=>window.setClip(n),name);await page.waitForTimeout(duration*500);await page.screenshot({path:path.join(local,'webgl-'+name+'-v2.png')});await page.waitForTimeout(duration*500+150);}
const video=await page.evaluate(()=>window.stopRecord());await fs.writeFile(path.join(local,'motion-review-v2.webm'),Buffer.from(video));await context.close();await browser.close();server.close();if(createHash('sha256').update(await fs.readFile(path.join(candidate,'coccosteus.glb'))).digest('hex')!==sourceGlbSha256)throw Error('Source changed during playback review');await fs.writeFile(path.join(local,'playback-validation-v2.json'),JSON.stringify({sourceGlbSha256,audit,errors,videoSha256:createHash('sha256').update(Buffer.from(video)).digest('hex')},null,2));console.log(JSON.stringify({clips:audit.length,errors,video:path.join(local,'motion-review-v2.webm')}));
