"""Freeze local preview only; parent handles publication."""
from pathlib import Path
from PIL import Image
import json,hashlib,datetime
here=Path(__file__).resolve().parent;root=here.parents[3];local=root.parent/'devonian-authoring/palaeoisopus';out=local/'v1-candidate'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
files=['palaeoisopus'+s for s in ['.glb','.lod1.glb','.json','.png','.select.png','.card.png','.thumb.png']];source=local/'palaeoisopus-v1.blend'
manifest={'id':'palaeoisopus','status':'preview','frozenAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':{f:{'sha256':sha(out/f),'bytes':(out/f).stat().st_size}for f in files},'editableSource':{'file':str(source),'sha256':sha(source)}}
v=json.loads((here/'validation.json').read_text());ex=json.loads((here/'export-review-v1.json').read_text());qa=json.loads((local/'viewer-final-preview/review.json').read_text());art=json.loads((here/'articulation-v1.json').read_text());assert len(qa['clips'])==19 and qa['errors']==[];assert art['sourceSha256']==sha(source);assert art['maximumArticulationGap']<.00002
for r in ex['exports']:assert r['sha256']==manifest['files'][Path(r['file']).name]['sha256']
portraits={}
for s in ['','.select','.card','.thumb']:
 p=out/('palaeoisopus'+s+'.png');im=Image.open(p);portraits[p.name]={'size':im.size,'mode':im.mode,'alphaRange':im.getchannel('A').getextrema()if'A'in im.getbands()else None}
report={'id':'palaeoisopus','status':'preview-ready','manifest':manifest,'geometry':{k:v[k]for k in ['fullTriangles','lodTriangles','reductionRatio','bones','fullBytes','lodBytes','anchorCount']},'eyes':art['eyes'],'articulation':{k:x for k,x in art.items()if k!='results'},'portraits':portraits,'actualGlbReview':'Final exact-export Idle,Swim,ventral proboscis and cephalic representative views plus LOD. Earlier19-action midpoint/directional review used the same unchanged authored actions before the final setal root/ventral-face correction; all558 roots quantitatively rechecked. Extended repeated screenshot sweep stopped per initial-roster priority. Still-frame review, not a claimed biomechanical playback validation.','runtimeValidation':'Direct decoded GLB finite normalized weights, 19/3 distinct actions, stable root, no scale channels, matching full/LOD138bone graph and3v1 sockets. Source every-frame finite bounds, loop/one-shot return seams and Death hold. Shared catalogue runtime audit deferred to parent registration.','knownPreviewLimitations':['Appendage articles, coxal rings and joints use shaped lofts with overlapping arthrodial tissue; subtle intersections and cuticle smoothing need the later art pass.','Cuticular ornament, cephalic sensory tubercles, setal density and colours are simplified; the body plan and differentiated limb article counts take priority in the initial roster.','Proboscis oral margin and lumen are articulated and attached; fine internal anatomy is inferred and deliberately minimal.','Actual eye positions unresolved; no eye globes are invented and ornamental tubercles are not mislabeled as eyes.','Exact swimming/probing/grasping movements are inferred from anatomy. Moult is a preparatory flex display, not simulated exuvium separation.']}
(out/'candidate-manifest.json').write_text(json.dumps(manifest,indent=2));(here/'final-review-v1.json').write_text(json.dumps(report,indent=2));print(json.dumps(manifest,indent=2))
