/** Lossless Meshopt storage for static proxies, with decoded before/after checks. */
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS,EXTMeshoptCompression} from '@gltf-transform/extensions';
import {MeshoptDecoder,MeshoptEncoder} from 'meshoptimizer';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'../../..'),local=path.resolve(root,'../devonian-authoring/props-instancing');const cfg=JSON.parse(await fs.readFile(path.join(import.meta.dirname,'config.json')));await Promise.all([MeshoptDecoder.ready,MeshoptEncoder.ready]);const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder,'meshopt.encoder':MeshoptEncoder});const sha=b=>createHash('sha256').update(b).digest('hex');const report=[];await fs.mkdir(path.join(local,'raw'),{recursive:true});
function canonical(a){const out=[];for(let i=0;i<a.length;i+=3){const tri=Array.from(a.slice(i,i+3)),j=tri.indexOf(Math.min(...tri));out.push(tri[j],tri[(j+1)%3],tri[(j+2)%3]);}return out;}
function values(doc){return doc.getRoot().listMeshes().flatMap(m=>m.listPrimitives().map(p=>({attributes:Object.fromEntries(p.listSemantics().sort().map(k=>[k,Array.from(p.getAttribute(k).getArray())])),indices:canonical(p.getIndices().getArray())})));}
for(const spec of cfg.props){const file=path.join(root,'public/assets/devonian/props-instanced',spec.id+'.glb');const bytes=await fs.readFile(file),doc=await io.readBinary(bytes);assert.equal(doc.getRoot().listMeshes().length,1);assert.equal(doc.getRoot().listAnimations().length,0);assert.equal(doc.getRoot().listSkins().length,0);assert.equal(doc.getRoot().listTextures().length,0);const prim=doc.getRoot().listMeshes()[0].listPrimitives()[0];assert.equal(doc.getRoot().listMeshes()[0].listPrimitives().length,1);assert.deepEqual(prim.getMaterial().getBaseColorFactor(),[1,1,1,1]);const before=values(doc);const pos=prim.getAttribute('POSITION'),color=prim.getAttribute('COLOR_0');assert(color);const triangles=prim.getIndices().getCount()/3;assert(triangles<=spec.triangles);const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];let radius=0;for(let i=0;i<pos.getCount();i++){const v=pos.getElement(i,[]);v.forEach((x,k)=>{assert(Number.isFinite(x));lo[k]=Math.min(lo[k],x);hi[k]=Math.max(hi[k],x)});radius=Math.max(radius,Math.hypot(v[0],v[2]));}assert(Math.abs(lo[1]-(spec.pivot==='center'?-1:0))<1e-5);assert(Math.abs(hi[1]-lo[1]-(spec.height??spec.dimensions[1]))<1e-5);if(spec.radius)assert(Math.abs(radius-spec.radius)<1e-5);let sum=0;for(let i=0;i<color.getCount();i++){const c=color.getElement(i,[]);assert(c.every(Number.isFinite));sum+=c[0]+c[1]+c[2];}const mean=sum/color.getCount()/3;assert(mean>0&&mean<.99);
 await fs.writeFile(path.join(local,'raw',spec.id+'.glb'),bytes);doc.createExtension(EXTMeshoptCompression).setRequired(true).setEncoderOptions({method:EXTMeshoptCompression.EncoderMethod.QUANTIZE});const packed=await io.writeBinary(doc);const decoded=await io.readBinary(packed);assert.deepEqual(values(decoded),before,'Storage compression must preserve geometry and pigment');await fs.writeFile(file,packed);report.push({id:spec.id,path:path.relative(root,file),sha256:sha(packed),bytes:packed.length,rawBytes:bytes.length,triangles,vertices:pos.getCount(),bounds:[lo,hi],radius,meanLinearPigment:mean,static:true,textures:0,materials:1,meshoptLossless:true});}
const sources=JSON.parse(await fs.readFile(path.join(local,'sources.json')));for(const s of sources)assert.equal(sha(await fs.readFile(s.source)),s.sha256,'Original metric specimen changed');await fs.writeFile(path.join(import.meta.dirname,'validation.json'),JSON.stringify({props:report,originalsUnchanged:true,proceduralExceptions:cfg.proceduralExceptions,triangles:report.reduce((s,p)=>s+p.triangles,0),bytes:report.reduce((s,p)=>s+p.bytes,0)},null,2));console.log(report.map(x=>({id:x.id,triangles:x.triangles,bytes:x.bytes})));console.log('PASS: static topology/pigment, budgets, exact placement dimensions, lossless Meshopt, source preservation');
