import {chromium} from 'playwright-core';import fs from 'node:fs';import path from 'node:path';
const out=path.resolve('../devonian-authoring/props-instancing/review');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const baseline=process.argv.includes('--baseline'),high=process.argv.includes('--high');const page=await browser.newPage({viewport:{width:1400,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const save=async name=>{const url=await page.evaluate(()=>document.querySelector('canvas').toDataURL('image/png'));fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(url.split(',')[1],'base64'));};
try{await page.route('**/scenery-qa.html',r=>r.fulfill({body:'<!doctype html><html><body style="margin:0"></body></html>',contentType:'text/html'}));await page.goto(`${process.env.DEVONIAN_QA_ORIGIN ?? 'http://127.0.0.1:4177'}/scenery-qa.html`);await page.evaluate(({b,h})=>{window.qaBaseline=b;window.qaHigh=h;},{b:baseline,h:high});const report=await page.evaluate(async()=>{
 const T=await import('/node_modules/.vite/deps/three.js');const {DEVONIAN}=await import('/src/content/devonian/index.ts');const {selectEra}=await import('/src/content/index.ts');selectEra(window.qaBaseline?{...DEVONIAN,environment:{...DEVONIAN.environment,floraProps:{}},assets:{...DEVONIAN.assets,props:'assets/props/',instancedScenery:undefined}}:DEVONIAN);const {loadPropGeometry}=await import('/src/render/props.ts');const {DEVONIAN_SCENERY}=await import('/src/content/devonian/scenery.ts');const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1400,900);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;document.body.appendChild(renderer.domElement);window.qaRenderer=renderer;
 const scene=new T.Scene();scene.background=new T.Color('#13262c');scene.add(new T.HemisphereLight('#e0f1ec','#3c443d',2));const sun=new T.DirectionalLight('#ffead2',3);sun.position.set(3,9,5);scene.add(sun);const cam=new T.PerspectiveCamera(36,1400/900,.01,100);const rows=[];
 for(const [i,id]of Object.keys(DEVONIAN_SCENERY.props).entries()){const g=await loadPropGeometry(id,'/',DEVONIAN_SCENERY);g.computeBoundingBox();const b=g.boundingBox,s=b.getSize(new T.Vector3());const m=new T.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:.85,side:T.DoubleSide});const mesh=new T.Mesh(g,m);const scale=1.7/Math.max(s.x,s.y,s.z);mesh.scale.setScalar(scale);mesh.position.set((i%4-1.5)*2.4-b.getCenter(new T.Vector3()).x*scale,-b.min.y*scale,Math.floor(i/4)*2.9);scene.add(mesh);rows.push({id,triangles:g.index.count/3,bounds:[b.min.toArray(),b.max.toArray()],color:g.getAttribute('color').count});}
 const ground=new T.Mesh(new T.PlaneGeometry(14,13),new T.MeshStandardMaterial({color:'#4d615b',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.set(0,-.02,3);scene.add(ground);cam.position.set(10,12,17);cam.lookAt(0,.2,3);renderer.render(scene,cam);window.qa={T,renderer,scene,cam};return {props:rows};});await save('static-proxy-contact');
 report.game=await page.evaluate(async()=>{const {T,renderer}=window.qa;const {createSea}=await import('/src/render/sea.ts');const {generateWorld,sampleHeight}=await import('/src/sim/world.ts');const scene=new T.Scene(),world=generateWorld(5052026);const sea=createSea(scene,world,window.qaHigh?'high':'low');const p=new T.Vector3(0,sampleHeight(0,0)+2,0);sea.prime(0,0,85);for(let i=0;i<80;i++)sea.update(i*.016,.016,p);await new Promise(resolve=>setTimeout(resolve,1200));const cam=new T.PerspectiveCamera(52,1400/900,.05,130);cam.position.set(8,sampleHeight(0,0)+8,14);cam.lookAt(0,sampleHeight(0,0)+1,-6);sea.setViewLength(2,cam.position.x,cam.position.z,cam.position.y);renderer.render(scene,cam);window.qaGame={scene,world,sea,cam};const props=[];scene.traverse(o=>{if(o.isInstancedMesh&&o.geometry.name.startsWith('devonian-'))props.push({geometry:o.geometry.name,instances:o.count,triangles:o.geometry.index.count/3,bend:!!o.geometry.getAttribute('aBend')})});const all=[];scene.traverse(o=>{if(o.isInstancedMesh)all.push({name:o.name,geometry:o.geometry.name,instances:o.count,triangles:(o.geometry.index?.count??o.geometry.getAttribute('position').count)/3,visible:o.visible})});if(!all.some(o=>o.name==='flora-crinoid'))throw Error('QA era import was stale: expected Devonian flora');return {quality:window.qaHigh?'high':'low',stats:sea.stats(),render:structuredClone(renderer.info.render),props,all};});await save((baseline?'devonian-game-baseline':'devonian-game')+(high?'-high':''));
 report.dispose=await page.evaluate(()=>{const {renderer}=window.qa;window.qaGame.sea.dispose();renderer.render(new window.qa.T.Scene(),window.qaGame.cam);return {groupDetached:window.qaGame.sea.group.parent===null,geometryMemory:renderer.info.memory.geometries};});
 report.errors=errors;fs.writeFileSync(path.join(out,(baseline?'baseline':'review')+(high?'-high':'')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(errors.length)throw Error(errors.join('\n'));
}finally{await browser.close();}
