// Generate src/content/cambrian/equivalent-sizing.json from the size research: what each Cambrian
// animal would be if the roster carried its real relative size. Run `npm run cambrian:sizes` after
// editing docs/research/cambrian-sizes.json or the constants here, and commit both; `--check` is
// what `npm run eras` runs, and fails if the committed table has drifted from the research.
//
// This is an *option*, off by default (Settings → Equivalent sizing). Nothing here touches
// creatures.ts: the shipped roster is unchanged and the simulation merges this table over it only
// when the setting is on (`setEquivalentSizing` in src/sim/creatures.ts).
//
// Length. The real animals span 1.55-37.8 cm, 24:1, against a roster that spans 1.5:1 — every
// Cambrian animal grows to within a third of every other, so an Apex Marrella finishes a match the
// size of an Apex Anomalocaris. Game length = K * metres^EXP puts them back in the real order and
// in something like real proportion, without changing how big the Cambrian sea is: K is set so the
// largest animal lands exactly on today's largest (Anomalocaris at 3.9 units, an Apex at 10.1), and
// EXP so the smallest still has a body worth swimming — the roster comes out 1.09-3.90 rather than
// 2.6-3.9, which is variance inside the scale the game already has. This is deliberately *not* the
// Devonian's exponent: that sea is built at a different scale for an 80:1 roster, and the thing
// worth sharing between the two is that adults differ at all, not the number they differ by.
//
// Speed, health and poise come along with the length so the sim is unchanged at any given body
// size. Nothing here is new tuning: it is the shipped tuning re-expressed for a body that is now a
// different number of units long.
//
//   speed  x r        a velocity, so it holds the animal's body lengths per second. The follow
//                     camera also sits a fixed number of body lengths back, so the on-screen pace
//                     barely moves either (the screens/s column).
//   hp     x r^1.1    `applyScaleStats` grows health as scale^1.1 of the adult figure, so lifting
//   poise  x r^1.1    the adult figure by the same power leaves health at a given *length* exactly
//                     where it was. Two bodies the same size still trade the same blows.
//
// Damage, knockback and reach need nothing: combat's `sizeFactor` is a ratio of lengths, and lunge,
// sense, clearance and body radius are all counted in body lengths already.
import fs from 'node:fs';

const K = 5.75, EXP = 0.4;
/** Everything hatches this long: src/sim/tiers.ts owns the same number. */
const LARVA_LENGTH = 0.75, APEX = 2.6;
const mag = (L) => L * 1.45 + 1.15 + Math.max(0, 0.8 - L) * 0.9;   // magnificationDistance, src/render/engine.ts
const r2 = (v) => Math.round(v * 100) / 100;

const research = JSON.parse(fs.readFileSync('docs/research/cambrian-sizes.json', 'utf8'));
const OUT = 'src/content/cambrian/equivalent-sizing.json';
const source = ['src/content/cambrian/creatures.ts', 'src/content/cambrian/expansion.ts']
  .map((f) => fs.readFileSync(f, 'utf8')).join('\n');
const check = process.argv.includes('--check');

/** The animal's own object literal in the roster source: from its id to the next one. */
function shipped(id) {
  const start = source.indexOf(`id: '${id}',`);
  if (start < 0) throw new Error(`${id} is not on the Cambrian roster`);
  const next = source.indexOf("id: '", start + 6);
  const seg = source.slice(start, next < 0 ? source.length : next);
  const f = (name, fallback) => {
    const m = seg.match(new RegExp(`\\b${name}: ([0-9.]+)`));
    return m ? Number(m[1]) : fallback;                 // the expansion helper's defaults
  };
  return { adultLength: f('adultLength', 3), speed: f('speed', 4.8), hp: f('hp', 90), poise: f('poise', 45) };
}

const rows = research.map((r) => {
  const was = shipped(r.id);
  const adultLength = r2(K * Math.pow(r.lengthM, EXP));
  const ratio = adultLength / was.adultLength;
  return {
    id: r.id, m: r.lengthM, was, ratio,
    adultLength, speed: r2(was.speed * ratio),
    hp: Math.round(was.hp * Math.pow(ratio, 1.1)),
    poise: Math.round(was.poise * Math.pow(ratio, 1.1)),
  };
});
const table = Object.fromEntries(rows.map((r) => [r.id, { adultLength: r.adultLength, speed: r.speed, hp: r.hp, poise: r.poise, realCm: Math.round(r.m * 1000) / 10 }]));
const body = {
  _: 'Generated by npm run cambrian:sizes from docs/research/cambrian-sizes.json. Do not edit by hand.',
  formula: `adultLength = ${K} * metres^${EXP}; speed x r; hp and poise x r^1.1, where r is the change in length`,
  note: 'realCm is the animal itself, for the selection card — the length the game figure is derived from, not a game figure.',
  larvaLength: LARVA_LENGTH,
  sizes: table,
};
const text = JSON.stringify(body, null, 2) + '\n';

if (check) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have === text) { console.log(`PASS: ${rows.length} equivalent-sizing entries match the size research`); process.exit(0); }
  console.error(`FAIL: ${OUT} is out of step with docs/research/cambrian-sizes.json — run npm run cambrian:sizes`);
  process.exit(1);
}
fs.writeFileSync(OUT, text);

console.log(`${OUT}: ${rows.length} animals\n`);
console.log('id                 real_m  adult   larva    apex  |  shipped   speed  (was)     hp  poise   screens/s (was)');
for (const r of rows.sort((a, b) => b.adultLength - a.adultLength)) {
  const larva = r2(Math.min(r.adultLength * 0.8, LARVA_LENGTH));
  console.log(`${r.id.padEnd(16)} ${r.m.toFixed(4)}  ${r.adultLength.toFixed(2).padStart(5)}   ${larva.toFixed(2)}  ${(r.adultLength * APEX).toFixed(1).padStart(5)}  |   ${r.was.adultLength.toFixed(2).padStart(5)}  ${r.speed.toFixed(2).padStart(5)}  ${r.was.speed.toFixed(1).padStart(5)}  ${String(r.hp).padStart(5)}  ${String(r.poise).padStart(5)}   ${(r.speed / mag(r.adultLength)).toFixed(2)}  (${(r.was.speed / mag(r.was.adultLength)).toFixed(2)})`);
}
