/**
 * Event kind → Devonian sample files, registered by the /devonian/ entry before the audio library
 * preloads. Names carry the era prefix so sfxUrl resolves them under assets/devonian/sfx/ while
 * the shared Cambrian table keeps serving everything not listed here. Generated by
 * tools/gen-sfx.mjs --set devonian; see docs/audio-requests.md.
 */
export const DEVONIAN_SAMPLES: Record<string, string[]> = {
  armour: ['devonian/armour-clang-1', 'devonian/armour-clang-2'],
  armourPierce: ['devonian/armour-pierce'],
  gulp: ['devonian/air-gulp'],
  airLow: ['devonian/air-low'],
  anoxia: ['devonian/anoxia-warning'],
  jet: ['devonian/jet-1', 'devonian/jet-2'],
  withdraw: ['devonian/withdraw'],
  moult: ['devonian/moult-crack'],
  shoalJoin: ['devonian/shoal-join'],
  rangeClaim: ['devonian/range-claim'],
  rangeLost: ['devonian/range-lost'],
  standingUp: ['devonian/standing-up'],
  dominant: ['devonian/dominant'],
  beach: ['devonian/beach'],
  shellCrush: ['devonian/shell-crush'],
  // per-creature specials: the engine plays `ability:<abilityId>` when a sample is registered for it
  'ability:jawShear': ['devonian/jaw-shear'], 'ability:runThrough': ['devonian/run-through'], 'ability:tuskLunge': ['devonian/tusk-lunge'],
  'ability:crushBite': ['devonian/crush-bite'], 'ability:neckSnap': ['devonian/neck-snap'], 'ability:cheliceraeGrab': ['devonian/chelicerae-grab'],
  'ability:tridentShove': ['devonian/trident-shove'], 'ability:shieldPush': ['devonian/shield-push'], 'ability:armourFlank': ['devonian/armour-flank'],
  'ability:brushDisplay': ['devonian/brush-display'], 'ability:shoalDart': ['devonian/shoal-dart'], 'ability:limbHaul': ['devonian/limb-haul'],
  'ability:shellHover': ['devonian/shell-hover'], 'ability:floorSweep': ['devonian/floor-sweep'], 'ability:filterGulp': ['devonian/filter-gulp'],
  'ability:shellJet': ['devonian/jet-1', 'devonian/jet-2'],
};
