import shapes from './prop-shapes.json';
import { ACTIVE_ERA } from './index';
import { ROUND, type Footprint } from '../sim/footprint';

/**
 * The measured shape of every instanced scenery prop, and which prop the active era draws each
 * piece of scenery with. Generated by `npm run shapes` from the GLBs themselves; the simulation
 * collides against these numbers because it never loads a mesh (see `src/sim/footprint.ts`).
 */
export interface PropShape {
  /** Vertical span in the prop's own space. A rock is centred on 0; a plant stands on it. */
  y0: number; y1: number;
  /** The furthest the footprint reaches. */
  rmax: number;
  /** Sixteen footprint radii from +z toward +x: the whole silhouette. */
  r: number[];
  /** The same radii measured again in each of five height bands, bottom to top. */
  bands: number[][];
}
const SHAPES = shapes as Record<string, PropShape>;

export const propShape = (id: string | undefined): PropShape | undefined => (id ? SHAPES[id] : undefined);

/** The prop id the active era draws a plant kind with, if it has one. */
export function floraPropId(kind: string): string | undefined {
  const scenery = ACTIVE_ERA.assets.instancedScenery;
  if (scenery) return (scenery.flora as Record<string, string | undefined>)[kind];
  const named = ACTIVE_ERA.environment.floraProps as Record<string, string | undefined> | undefined;
  return (named ?? { cushion: 'cushion-sponge', lettuce: 'lettuce-tuft', spine: 'spine-sponge', glass: 'glass-fan' })[kind];
}

/** The prop id the active era draws a rock with. `undefined` variant is the plain boulder. */
export function rockPropId(variant?: 'blade-spire' | 'talus-shard'): string | undefined {
  const rocks = ACTIVE_ERA.assets.instancedScenery?.rocks as Record<string, string | undefined> | undefined;
  const slot = variant ?? 'boulder';
  // Without a scenery pack the Cambrian draws the spires and shards from its own props folder and
  // the plain boulder from a procedural unit rock, which is already the circle the collider assumed.
  return rocks?.[slot] ?? (variant ? variant : undefined);
}

export const footprintOf = (id: string | undefined): Footprint => propShape(id)?.r ?? ROUND;
