import shapes from './prop-shapes.json';
import { ACTIVE_ERA } from './index';
import { ROUND, type Footprint } from '../sim/footprint';

/**
 * The measured shape of every instanced scenery prop, and which prop the active era draws each
 * piece of scenery with. Generated by `npm run shapes` from the GLBs themselves; the simulation
 * collides against these numbers because it never loads a mesh (see `src/sim/footprint.ts`).
 */
export interface PropShape {
  /** Vertical span in the prop's own space. A rock is centred on 0; a plant stands on it. */
  y0: number; y1: number;
  /** The furthest the footprint reaches. */
  rmax: number;
  /** Sixteen footprint radii from +z toward +x: the whole silhouette. */
  r: number[];
  /** The same radii measured again in each of five height bands, bottom to top. */
  bands: number[][];
}
const SHAPES = shapes as Record<string, PropShape>;

export const propShape = (id: string | undefined): PropShape | undefined => (id ? SHAPES[id] : undefined);

/** Every prop the active era draws a plant kind with: one id, or a family's variants in order. */
export function floraPropIds(kind: string): readonly string[] {
  const scenery = ACTIVE_ERA.assets.instancedScenery;
  const named = scenery
    ? (scenery.flora as Record<string, string | readonly string[] | undefined>)[kind]
    : (ACTIVE_ERA.environment.floraProps as Record<string, string | undefined> | undefined
      ?? { cushion: 'cushion-sponge', lettuce: 'lettuce-tuft', spine: 'spine-sponge', glass: 'glass-fan' })[kind];
  return named === undefined ? [] : typeof named === 'string' ? [named] : named;
}

/** The prop id the active era draws a plant kind with, if it has one — the first of a family. */
export const floraPropId = (kind: string): string | undefined => floraPropIds(kind)[0];

/**
 * What a plant kind collides as. One prop is its own measured shape; a family of variants is the
 * *union* of theirs — the widest radius each band reaches over all of them, and the tallest span.
 * The simulation places one collider per kind and never learns which variant was drawn, so the
 * envelope has to cover the one that was: a collider smaller than the mesh is a body the player
 * can swim through the side of.
 */
export const propShapeFor = (kind: string): PropShape | undefined => unionShape(floraPropIds(kind));

/** The envelope a list of props share, band by band. One id is simply its own shape. */
export function unionShape(ids: readonly string[]): PropShape | undefined {
  const shapes = ids.map(propShape).filter((s): s is PropShape => !!s);
  if (shapes.length < 2) return shapes[0];
  return {
    y0: Math.min(...shapes.map((s) => s.y0)),
    y1: Math.max(...shapes.map((s) => s.y1)),
    rmax: Math.max(...shapes.map((s) => s.rmax)),
    r: shapes[0].r.map((_, i) => Math.max(...shapes.map((s) => s.r[i]))),
    bands: shapes[0].bands.map((band, b) => band.map((_, i) => Math.max(...shapes.map((s) => s.bands[b][i])))),
  };
}

/** The prop id the active era draws a rock with. `undefined` variant is the plain boulder. */
export function rockPropId(variant?: 'blade-spire' | 'talus-shard'): string | undefined {
  const rocks = ACTIVE_ERA.assets.instancedScenery?.rocks as Record<string, string | undefined> | undefined;
  const slot = variant ?? 'boulder';
  // Without a scenery pack the Cambrian draws the spires and shards from its own props folder and
  // the plain boulder from a procedural unit rock, which is already the circle the collider assumed.
  return rocks?.[slot] ?? (variant ? variant : undefined);
}

export const footprintOf = (id: string | undefined): Footprint => propShape(id)?.r ?? ROUND;
