import type { CreatureDef, MoveDef } from './creatures';

const bite = (name: string, damage = 8, extra: Partial<MoveDef> = {}): MoveDef => ({
  name, damage, windup: .14, active: .16, recovery: .22, poise: 12, knockback: 1.2, stamina: 6, lunge: .25, ...extra,
});
const heavy = (name: string, damage = 20, extra: Partial<MoveDef> = {}): MoveDef => ({
  name, damage, windup: .4, active: .2, recovery: .5, poise: 38, knockback: 3, stamina: 18, lunge: .65, guardBreak: true, ...extra,
});
const animal = (d: Pick<CreatureDef, 'id' | 'name' | 'species' | 'tagline' | 'role' | 'color' | 'ability' | 'abilityName' | 'abilityDesc' | 'passive' | 'weakness' | 'light' | 'heavy'> & Partial<CreatureDef>): CreatureDef => ({
  ground: false, adultLength: 3, speed: 4.8, burst: 1.8, agility: 4, turnRate: 2.8, glide: .9,
  hp: 90, poise: 45, stamina: 110, defense: .06, sense: 10, accent: '#d5eee3', canGuard: true,
  abilityCooldown: 12, abilityDuration: 3.6, abilityLoop: true, mobileAbility: true,
  provenance: 'Burgess Shale', proceduralUndulation: false, ...d,
});

/** Biological inspiration is documented separately from invented combat mechanics. */
export const EXPANSION_CREATURES: readonly CreatureDef[] = [
  animal({ id: 'pikaia', name: 'Pikaia', species: 'P. gracilens', role: 'Evasive forager',
    tagline: 'A ribbon of muscle. One bend ahead of danger.', color: '#d2a8a2',
    speed: 6.2, agility: 6.2, turnRate: 4.2, hp: 70, poise: 28, bodyRadius: .12, diet: 'deposit',
    light: bite('Head flick', 5), heavy: heavy('Ribbon lash', 12, { sweep: true, knockback: 5 }),
    ability: 'ribbonSlip', abilityName: 'Ribbon slip', abilityCooldown: 10,
    abilityDesc: 'Break tracking, evade the opening hit, then weave at increased speed for 3.6 seconds.',
    passive: 'Narrow body; forages microbial mats near the bottom.', weakness: 'Little armor and weak direct damage.' }),
  animal({ id: 'nectocaris', name: 'Nectocaris', species: 'N. pteryx', role: 'Tentacle grappler',
    tagline: 'Fins whisper. Tentacles close.', color: '#9ab9ce', speed: 5.2, agility: 5.6, turnRate: 3.8,
    light: bite('Tentacle pinch', 8), heavy: heavy('Paired seize', 18, { grab: true, knockback: 0 }),
    ability: 'tentacleSeize', abilityName: 'Tentacle seize', abilityDuration: 1.2,
    abilityDesc: 'Reach forward, pull a nearby target inward, and clamp with both tentacles.',
    passive: 'Quick turning and long-reach capture.', weakness: 'Fragile when its capture misses.' }),
  animal({ id: 'burgessomedusa', name: 'Burgessomedusa', species: 'B. phasmiformis', role: 'Tentacle corral',
    tagline: 'A beating bell with a dangerous fringe.', color: '#e9a9ba', speed: 3.5, burst: 1.6, agility: 2.6, turnRate: 2,
    hp: 110, poise: 55, bodyRadius: .29, clearance: .5,
    light: bite('Tentacle brush', 7, { sweep: true }), heavy: heavy('Bell recoil', 16, { sweep: true, knockback: 7, lunge: .1 }),
    ability: 'bellCorral', abilityName: 'Bell corral',
    abilityDesc: 'Spread the fringe for 3.6 seconds; nearby enemies take one sting and are pushed away.',
    passive: 'Circular attacks cover every approach.', weakness: 'Slow acceleration and a broad, soft target.' }),
  animal({ id: 'odaraia', name: 'Odaraia', species: 'O. alata', role: 'Cruising collector',
    tagline: 'Three tail fins. A living submarine.', color: '#b6c1a0', diet: 'filter', speed: 5.4, glide: .35, turnRate: 1.9, defense: .18,
    light: bite('Limb comb', 6), heavy: heavy('Carapace shove', 16, { knockback: 6 }),
    ability: 'collectorWake', abilityName: 'Collector wake',
    abilityDesc: 'Open a broad feeding current: draw in small wild snacks and filter blooms at triple rate.',
    passive: 'Feeds on plankton blooms at every growth tier; long glide.', weakness: 'Wide turning circle and modest damage.' }),
  animal({ id: 'ottoia', name: 'Ottoia', species: 'O. prolifica', role: 'Burrowing ambusher',
    tagline: 'The sediment has teeth.', color: '#c4a28a', ground: true, speed: 3.8, glide: 3, hp: 110, poise: 60, clearance: .15,
    light: bite('Introvert snap', 9), heavy: heavy('Hooked thrust', 22, { lunge: 1.1 }),
    ability: 'sedimentDive', abilityName: 'Sediment dive',
    abilityDesc: 'Travel beneath the sediment for 2.4 seconds, then emerge with a hooked strike. Protection lasts only at entry.',
    abilityDuration: 2.4, passive: 'Retractile body and a long forward strike.', weakness: 'Restricted to the bottom; vulnerable after emerging.' }),
  animal({ id: 'cambroraster', name: 'Cambroraster', species: 'C. falcatus', role: 'Basket sweeper',
    tagline: 'A shield overhead. A net beneath.', color: '#ba956b', adultLength: 3.8, speed: 3.9, turnRate: 1.8, hp: 135, poise: 85, defense: .27, bodyRadius: .33,
    light: bite('Basket rake', 8, { sweep: true }), heavy: heavy('Shield sweep', 23, { sweep: true, knockback: 5 }),
    ability: 'basketRake', abilityName: 'Basket rake', abilityDuration: 1.2,
    abilityDesc: 'Sweep a broad forward arc, drag smaller prey inward, and expose concealed creatures in reach.',
    passive: 'Broad feeding sweep and sturdy head shield.', weakness: 'Large collision profile; slow turns.' }),
  animal({ id: 'sidneyia', name: 'Sidneyia', species: 'S. inexpectans', role: 'Shell crusher',
    tagline: 'Get underneath the armor.', color: '#b68b7b', ground: true, speed: 4.5, glide: 2.4, hp: 120, poise: 70, defense: .2,
    light: bite('Gnathobase pinch', 10), heavy: heavy('Crushing clamp', 24, { armorPierce: .5, knockback: 1 }),
    ability: 'shellCrush', abilityName: 'Shell crush', abilityDuration: 1.2,
    abilityDesc: 'Clamp a target in front: a heavy strike bypasses three quarters of its armor and breaks guard.',
    passive: 'Heavy attacks bypass half of armor reduction.', weakness: 'Short reach and committed wind-up.' }),
  animal({ id: 'leanchoilia', name: 'Leanchoilia', species: 'L. superlata', role: 'Sensory sweeper',
    tagline: 'Feel the reef before it feels you.', color: '#aa9bc7', sense: 17, hp: 80, turnRate: 3.5,
    light: bite('Great-appendage pinch', 7), heavy: heavy('Whiplash sweep', 17, { sweep: true, knockback: 4 }),
    ability: 'whipSearch', abilityName: 'Whip search',
    abilityDesc: 'Sweep long feelers: reveal nearby animals and draw small wild snacks toward you.',
    passive: 'Long sensory range; sweeping heavy attack.', weakness: 'Weak armor and limited finishing power.' }),
  animal({ id: 'isoxys', name: 'Isoxys', species: 'I. acutangulus', role: 'Interception predator',
    tagline: 'A needle-shaped shadow crosses your path.', color: '#cf9c60', speed: 6, burst: 2, turnRate: 2.2, defense: .16,
    light: bite('Raptorial nip', 8), heavy: heavy('Spined intercept', 21, { lunge: 1.5 }),
    ability: 'spineIntercept', abilityName: 'Spine intercept', abilityDuration: 1.2, mobileAbility: false,
    abilityDesc: 'Commit to a fast forward pass, striking each enemy in your path once.',
    passive: 'Fast cruising with a protective carapace.', weakness: 'Committed trajectory during its signature pass.' }),
  animal({ id: 'odontogriphus', name: 'Odontogriphus', species: 'O. omalus', role: 'Surface grazer',
    tagline: 'Stay low. Keep the feeding ribbon moving.', color: '#c3b66e', ground: true, speed: 3.7, glide: 3, clearance: .06, bodyRadius: .18, diet: 'grazer',
    hp: 100, poise: 65, light: bite('Radula rasp', 6), heavy: heavy('Foot shove', 14, { knockback: 6 }),
    ability: 'adhesiveGlide', abilityName: 'Adhesive glide',
    abilityDesc: 'Keep crawling with reduced damage and knockback; graze microbial mats at triple rate.',
    passive: 'Low body clearance; grazes microbial mats while moving.', weakness: 'Little reach and no hard armor.' }),
  animal({ id: 'ctenorhabdotus', name: 'Ctenorhabdotus', species: 'C. capulus', role: 'Ciliary drifter',
    tagline: 'Twenty-four comb rows carry you through the blue.', color: '#a5d4d0', speed: 4.2, glide: .2, hp: 75, poise: 30, diet: 'filter', clearance: .63,
    light: bite('Oral catch', 5), heavy: heavy('Body deflection', 12, { sweep: true, knockback: 6 }),
    ability: 'combCruise', abilityName: 'Comb cruise',
    abilityDesc: 'Accelerate smoothly, recover stamina, and reduce incoming damage for 3.6 seconds.',
    passive: 'Long glide; consumes bloom particles at all tiers.', weakness: 'Soft body and low damage.' }),
  animal({ id: 'vetulicola', name: 'Vetulicola', species: 'V. cuneata', role: 'Pumping swimmer',
    tagline: 'A chamber, a tail, and a current of food.', color: '#aabfa2', provenance: 'Chengjiang · Early Cambrian', diet: 'filter', hp: 100, poise: 55, speed: 4.6,
    light: bite('Mouth bump', 6), heavy: heavy('Tail sweep', 16, { sweep: true, knockback: 5 }),
    ability: 'pharyngealPump', abilityName: 'Pharyngeal pump',
    abilityDesc: 'Beat the tail and open the feeding chamber: faster swimming and quadruple bloom intake.',
    passive: 'Feeds on bloom particles at every growth tier.', weakness: 'Little armor; benefits most from finding blooms.' }),
  animal({ id: 'tamisiocaris', name: 'Tamisiocaris', species: 'T. borealis', role: 'Plankton harvester',
    tagline: 'Comb the water. Grow on the smallest life.', color: '#d2b891', provenance: 'Sirius Passet · Early Cambrian', diet: 'filter', adultLength: 3.8,
    hp: 125, poise: 65, speed: 4.5, turnRate: 2, light: bite('Filter brush', 5, { sweep: true }), heavy: heavy('Flap sweep', 14, { sweep: true, knockback: 7 }),
    ability: 'planktonComb', abilityName: 'Plankton comb',
    abilityDesc: 'Spread the filtering combs: gather small wild snacks in front and harvest blooms at five times the normal rate.',
    passive: 'Specialist bloom feeder at every growth tier.', weakness: 'Low damage and a broad exposed feeding apparatus.' }),
];
