import { creature, type CreatureId } from './creatures';
import { TIER_SCALE, type Tier } from './types';

/**
 * The Cambrian growth ladder's *sizes*, per creature.
 *
 * Larva → Juvenile → Adult → Giant → Apex used to be one set of multipliers for the whole roster,
 * which only worked because the whole roster was one size: every animal grew to within a third of
 * every other, so an Apex Marrella — an animal you could rest on a fingernail — ended a match as
 * long as an Apex Anomalocaris. `docs/research/cambrian-sizes.md` puts the real lengths back
 * (`adultLength`, generated by `npm run cambrian:sizes`), and this is the other half of it: the
 * ladder now runs from a length everything shares to a length that is the animal's own.
 *
 * **Everything hatches the same size.** A larva is `LARVA_LENGTH` long whatever it will grow into,
 * so the roster starts level and size is something you earn rather than something you pick. Growth
 * to Adult is geometric from there — each moult multiplies the body by the same factor, so the
 * animals with further to go grow faster per moult — and the two rungs past Adult keep their old
 * multiples of the adult body, because Giant and Apex were never biology in the first place.
 *
 * This is the Devonian's rule (`stageScale` in src/sim/devonian/state.ts) applied to the Cambrian's
 * five rungs. The one difference is where adulthood sits: the Devonian moults three times to reach
 * it and then has Prime above, the Cambrian twice with Giant and Apex above.
 */
export const ADULT_TIER = 2;
/** The length everything is at Larva, and the shortest body the engine draws well. */
export const LARVA_LENGTH = 0.75;
/** Larva length for a creature that grows to `adultLength` — the smallest animals hatch smaller. */
export const larvaLength = (adultLength: number) => Math.min(adultLength * 0.8, LARVA_LENGTH);

/** Body scale (of adult length) at `tier`, for the creature that has to do the growing. */
export function tierScale(id: CreatureId, tier: number): number {
  const t = Math.max(0, Math.min(TIER_SCALE.length - 1, Math.round(tier))) as Tier;
  if (t >= ADULT_TIER) return TIER_SCALE[t];
  const adult = creature(id).adultLength;
  const s0 = larvaLength(adult) / adult;
  return Math.pow(s0, 1 - t / ADULT_TIER);          // s0 → 1 over the two moults to adult
}

/** The tier a body of `scale` stands on: the largest whose scale it has reached. */
export function tierForScale(id: CreatureId, scale: number): Tier {
  let best: Tier = 0;
  for (let i = 0; i < TIER_SCALE.length; i++) if (scale >= tierScale(id, i) * 0.98) best = i as Tier;
  return best;
}
