import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import sharp from 'sharp';
import {NodeIO}from'@gltf-transform/core';import{ALL_EXTENSIONS}from'@gltf-transform/extensions';import{MeshoptDecoder}from'meshoptimizer';await MeshoptDecoder.ready;
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder}), H='tools/triassic/creatures/shonisaurus', L='local/triassic-authoring/shonisaurus/lip-material-fix';const sha=x=>crypto.createHash('sha256').update(x).digest('hex');const data=a=>Array.from(a.getArray());
const full=await io.read('public/assets/triassic/creatures/shonisaurus.glb'), old=await io.read(`${L}/before.glb`), raw=await io.read(`${H}/tripo-raw/shonisaurus.raw.glb`);
function rig(d){const s=d.getRoot().listSkins()[0];return{joints:s.listJoints().map(n=>[n.getName(),n.getParentNode()?.getName(),n.getTranslation(),n.getRotation(),n.getScale()]),bind:data(s.getInverseBindMatrices()),clips:d.getRoot().listAnimations().map(a=>[a.getName(),a.listChannels().map(c=>[c.getTargetNode().getName(),c.getTargetPath(),data(c.getSampler().getInput()),data(c.getSampler().getOutput())]).sort((a,b)=>(a[0]+a[1]).localeCompare(b[0]+b[1]))]).sort((a,b)=>a[0].localeCompare(b[0]))};}assert.deepEqual(rig(full),rig(old));
const m=full.getRoot().listMaterials().find(m=>m.getName()==='Body skin');assert(m.getBaseColorTexture());assert(Math.abs(m.getNormalScale()-.15)<1e-6);assert(Math.abs(m.getRoughnessFactor()-.7)<1e-6);assert.equal(m.getMetallicFactor(),0);assert.equal(m.getDoubleSided(),false);
let vertices=0;for(const mesh of full.getRoot().listMeshes())for(const p of mesh.listPrimitives())if(p.getMaterial()===m){const a=p.getAttribute('COLOR_0');for(const v of a.getArray())assert.equal(v,a.getNormalized()?(a.getComponentType()===5123?65535:255):1);vertices+=a.getCount();}
const original=await sharp(raw.getRoot().listMaterials()[0].getBaseColorTexture().getImage()).ensureAlpha().raw().toBuffer(), restored=await sharp(m.getBaseColorTexture().getImage()).ensureAlpha().raw().toBuffer();assert.equal(original.length,restored.length);let max=0,sum=0;for(let i=0;i<original.length;i++){const d=Math.abs(original[i]-restored[i]);max=Math.max(max,d);sum+=d;}assert(max<=1);
const before=JSON.parse(fs.readFileSync(`${L}/before-lip.json`)),neutral=JSON.parse(fs.readFileSync(`${L}/neutral-lip.json`)),after=JSON.parse(fs.readFileSync(`${H}/lip-validation.json`));const lip=r=>({heavyAt035Seconds:r.samples.find(x=>x.clip==='Heavy'&&x.seconds===.35).invertedMouthFaces,maxAcrossSamples:Math.max(...r.samples.map(x=>x.invertedMouthFaces)),samples:r.samples.length});
const result={passed:true,authoredFileSha256:sha(fs.readFileSync('public/assets/triassic/creatures/shonisaurus.glb')),sourceAlbedoRestored:true,sourceAlbedoPixelDifference:{maximum8Bit:max,mean8Bit:sum/original.length},whiteColorVertices:vertices,normalScale:m.getNormalScale(),roughness:m.getRoughnessFactor(),metallic:0,singleSided:true,priorSkeletonAndClipsPreservedExactly:true,lipComparison:{metric:after.method,priorClosed:lip(before),priorNeutralOpen:lip(neutral),corrected:lip(after)},note:'Restore detailed original UV albedo instead of interpolated vertex-color bake; source markings remain. Cutaneous mandibular skin has separate ownership, with a smooth rear hinge blend.'};fs.writeFileSync(`${H}/material-audit.json`,JSON.stringify(result,null,2)+'\n');console.log(result);
