// Run from repo root: node --experimental-transform-types tools/feeding-test.mjs
import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';import{GLTFLoader}from 'three/addons/loaders/GLTFLoader.js';import{MeshoptDecoder}from 'three/addons/libs/meshopt_decoder.module.js';import{CreatureAnchors,feedingPhase}from '../src/render/anchors.ts';
globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:512,height:512,close(){}});
// Execute the production post-animation pass itself, without constructing a WebGL renderer.
const source=fs.readFileSync('src/render/engine.ts','utf8');const begin=source.indexOf('  private syncAttachments(game: Game) {')+'  private syncAttachments(game: Game) {'.length;const end=source.indexOf('\n  /** Per-viewport pass:',begin);let body=source.slice(begin,end).trim();body=body.slice(0,body.lastIndexOf('}')).replace(/new Set<number>\(\)/g,'new Set()');const pass=new Function('THREE','feedingPhase',`return function(game){${body}}`)(THREE,feedingPhase);
const bytes=fs.readFileSync('public/assets/creatures/opabinia.glb');const gltf=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');const model=gltf.scene,anchors=new CreatureAnchors(model),group=new THREE.Group();group.add(model);const mixer=new THREE.AnimationMixer(model),eat=mixer.clipAction(gltf.animations.find(c=>c.name==='Eat')).play();
const pv={group,anchors,visibleLength:5,poseFeeding(p){eat.time=p*.8;mixer.update(0);group.updateMatrixWorld(true);}};const preyGroup=new THREE.Group(),fv={group:preyGroup,visibleLength:.5};pv.poseFeeding(0);anchors.world('anchor_grasp',preyGroup.position);const originalPos=preyGroup.position.clone();const predator={id:1,creature:'opabinia',state:'eating',eatingTarget:2,stateT:0},food={id:2,state:'dead',pos:{x:originalPos.x,y:originalPos.y,z:originalPos.z},eaten:0};const game={actors:[predator,food],byId(id){return this.actors.find(a=>a.id===id)}};const context={views:new Map([[1,pv],[2,fv]]),feeding:new Map(),anchorPoint:new THREE.Vector3(),mouthPoint:new THREE.Vector3(),insidePoint:new THREE.Vector3()};const initialSim=JSON.stringify(food.pos);let heldError=0,lastScale=1;
for(let i=0;i<=98;i++){food.eaten=i/100;predator.stateT=i/100;preyGroup.position.copy(originalPos);preyGroup.scale.setScalar(1);pv.poseFeeding(0);pass.call(context,game);assert.equal(JSON.stringify(food.pos),initialSim);assert(preyGroup.position.toArray().every(Number.isFinite));if(i===50){const grip=new THREE.Vector3();anchors.world('anchor_grasp',grip);heldError=grip.distanceTo(preyGroup.position);assert(heldError<1e-5)}if(i===98){lastScale=preyGroup.scale.x;assert(lastScale<.01);const mouth=new THREE.Vector3();anchors.world('anchor_mouth_inside',mouth);assert(mouth.distanceTo(preyGroup.position)<.03)}}
predator.state='free';pass.call(context,game);assert.equal(context.feeding.size,0);const result={productionAttachmentPass:true,heldError,finalVisibleScale:lastScale,simulationPositionUnchanged:true,cancelledSessionCleared:true};console.log(result);
