// Generates the game's sound effects with the ElevenLabs sound-generation API.
// Usage: ELEVENLABS_API_KEY=... node tools/gen-sfx.mjs [only-name]
import fs from 'node:fs';
const KEY = process.env.ELEVENLABS_API_KEY;
if (!KEY) { console.error('ELEVENLABS_API_KEY not set'); process.exit(1); }
const OUT = 'public/assets/sfx';
const only = process.argv[2];
// Sounds reworked to be organic rather than metallic were generated at a lower prompt influence,
// which leaves the model room to make a real recording instead of reciting the adjectives.
const LOW_INFLUENCE = new Set(['grab', 'guard-break', 'ability', 'disintegrate', 'dodge', 'heartbeat', 'escape', 'ui-start', 'crunch', 'silt']);
// escape-alt.mp3 is the earlier take, kept as a backup; it is not generated by this script.

/** name, prompt, seconds, variants, loop */
export const MANIFEST = [
  ['bite', 'quick wet crunchy bite underwater, a small armored sea creature snapping its mouthparts shut, short punchy impact with a tiny bubble burst, no music', 0.6, 3],
  ['crunch', 'chewing a shell apart underwater: wet cracking and splintering as mouthparts grind through a carapace, close and detailed, crunchy and present, no music', 0.9, 2],
  ['hit-light', 'dull soft underwater body impact, a slap of flesh against carapace, thud with a short bubble fizz, no music', 0.5, 2],
  ['hit-heavy', 'heavy underwater impact, a large creature slamming into another, deep muffled boom with cracking shell and a bubble burst, no music', 0.8, 2],
  ['parry', 'dull hollow clack of two crab shells knocking together underwater, thick carapace deflecting a strike, dry woody knock with a quick damp decay, no metal, no ringing, no bell, no music', 0.5, 1],
  ['guard-break', 'a hard shell cracks apart: a sharp wet crack and splintering, then a heavy wet thud and a rush of bubbles, close and detailed, no metallic ring, no bell tone, no chime', 0.9, 1],
  ['stagger', 'muffled underwater tumble, a creature reeling and thrashing briefly, sand kicked up, short', 0.7, 1],
  ['dodge', 'a large fish flicks its tail and darts away: water displaced in a wet swishing surge with a burst of bubbles, close underwater recording, no wind, no air whoosh', 0.6, 2],
  ['burst', 'accelerating rush of water, a swimming creature surging forward at speed, whoosh building then trailing off, bubbles streaming', 1.2, 1],
  ['silt', 'a puff of sediment billows up from the seabed: a soft sandy whump followed by a fine hiss of particles settling through water, close and present, no music', 1.5, 1],
  ['grab', 'a wet squelching squeeze: strong appendages close around a soft struggling body underwater, thick suction squelch and a creaking wet grip, muffled struggle, close and detailed, no splash, no metal, no ring, no bell', 0.9, 1],
  ['kill', 'decisive heavy crunch of a shell being crushed underwater, final wet snap with a large burst of bubbles, no music', 1.4, 1],
  ['death', 'low slow groaning sink underwater, a creature going limp and drifting down, deep muffled tone fading with faint bubbles', 1.6, 1],
  ['tier-up', 'a creature moulting and growing underwater: a shell cracks open in a rising swell, deep whoomp then bright shimmering resonance, triumphant, short', 2.5, 1],
  ['hunted', 'ominous low cinematic sting underwater, a huge predator has noticed you, deep rumbling drone hit with a slow menacing swell, dark', 2.0, 1],
  ['escape', 'a held breath released underwater: warm relief, a soft rising hollow wooden tone with drifting bubbles and gentle water movement, calm and clean, no chime, no bell, no percussion', 1.6, 1],
  ['sense', 'sonar pulse underwater, a clean resonant ping that expands outward and fades, slightly organic', 1.2, 1],
  ['ability', 'subtle underwater magic: a soft warm swell blooms through the water with a gentle hollow resonance and a few rising bubbles, mysterious and restrained, organic, present but not loud, no chimes, no sparkle, no metallic shimmer, no hiss, no music', 1.2, 1],
  ['pounce', 'sudden lunge underwater, a predator launching itself forward, sharp water whoosh ending in a solid muffled body impact, no music', 0.8, 1],
  ['swallow', 'wet muffled gulp underwater, a large creature engulfing prey whole, thick slurping suction with a soft internal thud, no music', 1.1, 1],
  ['disintegrate', 'ethereal dissolve: a soft breathy airy wash with a faint hollow flute-like tone drifting apart and fading into nothing, weightless and dreamlike, gentle, no hiss, no static, no sparkle, no percussion', 1.0, 1],
  ['routed', 'an enemy breaking off and fleeing underwater, quick retreating water rush with a short falling tonal sigh, relief, no music', 1.2, 1],
  ['noticed', 'brief unsettling low sting underwater, something has just spotted you, short dark swell with a soft tap, subtle and quiet, no music', 0.9, 1],
  ['respawn', 'a tiny creature hatching underwater, soft shell crack then a gentle rising shimmer as it unfurls, warm and hopeful, short', 1.4, 1],
  ['heartbeat', 'a single close heartbeat: lub-dub, a soft thump followed by a firmer thump, each with a short muffled papery snap, warm body resonance, recorded against the chest, no music, no reverb', 1.0, 1],
  ['ui-move', 'very soft muted water droplet tap, gentle rounded low-volume UI tick, no sharp transients, quiet, very short', 0.5, 1],
  ['ui-confirm', 'soft gentle two-note rising marimba-like tone heard underwater, warm and rounded, muted, no harsh highs, quiet', 0.6, 1],
  ['ui-back', 'soft gentle two-note falling marimba-like tone heard underwater, warm and rounded, muted, no harsh highs, quiet', 0.6, 1],
  ['ui-join', 'gentle warm welcoming chime, a soft bubble pop then a smooth rising mellow tone, underwater, rounded and quiet, pleasant', 0.9, 1],
  ['ui-start', 'a warm rounded rising three-note flourish on a hollow wooden marimba, close and present, with a soft bubble swell underneath, mellow full mid-range, confident, no harsh transients, no metal, no reverb wash', 1.6, 1],
  ['won', 'triumphant short victory fanfare with an underwater ambience, warm resonant swell and shimmering high tones, concise', 3.5, 1],
  ['ambient-reef', 'calm underwater ambience on a shallow prehistoric reef: soft water movement, distant bubbles, gentle current wash, faint clicks of small creatures, no music, seamless loop', 22, 1, true],
  ['giant-drone', 'menacing low underwater drone, the presence of a huge predator nearby, deep slow pulsing rumble with sub bass, dark and tense, seamless loop', 12, 1, true],
];

async function gen(text, seconds, loop, influence = 0.45) {
  const body = { text, duration_seconds: seconds, prompt_influence: influence };
  if (loop) body.loop = true;
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch('https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_96', {
      method: 'POST', headers: { 'xi-api-key': KEY, 'Content-Type': 'application/json' }, body: JSON.stringify(body),
    });
    if (res.ok) return Buffer.from(await res.arrayBuffer());
    const msg = await res.text();
    if (res.status === 422 && body.loop) { delete body.loop; continue; } // older API without loop support
    console.error(`  ${res.status} ${msg.slice(0, 200)}`);
    if (res.status === 429) await new Promise((r) => setTimeout(r, 4000)); else break;
  }
  return null;
}

for (const [name, prompt, seconds, variants = 1, loop = false] of MANIFEST) {
  if (only && name !== only) continue;
  for (let v = 0; v < variants; v++) {
    const file = `${OUT}/${name}${variants > 1 ? `-${v + 1}` : ''}.mp3`;
    if (fs.existsSync(file) && !only) { console.log('skip', file); continue; }
    const buf = await gen(prompt, seconds, loop, LOW_INFLUENCE.has(name) ? 0.35 : 0.45);
    if (!buf) { console.error('FAILED', file); continue; }
    fs.writeFileSync(file, buf);
    console.log('ok', file, buf.length);
  }
}
