import assert from 'node:assert/strict';
import { Game } from '../src/sim/game';
import { emptyInput } from '../src/sim/types';
import { ladderMark, placeOnLadder } from '../src/sim/ladder';
import { MODE_IDS } from '../src/sim/types';
import { lengthOf } from '../src/sim/actors';

const setup = [{ creature: 'waptia' as const, device: 'keyboard' as const, ready: true }];
const survival = new Game('survival', setup, 31);
const rise = new Game('rise', setup, 31);
survival.skipHatch(); rise.skipHatch();
assert.deepEqual(MODE_IDS, ['rise', 'survival', 'reef']);
assert.equal(survival.players[0].hunger, 100);
const sp = survival.players[0], rp = rise.players[0];
sp.spawnProtect = rp.spawnProtect = 1000;
const before = ladderMark(survival, sp);
for (let i = 0; i < 60; i++) { survival.step(1 / 60, new Map([[0, emptyInput()]])); survival.events.length = 0; }
assert(sp.hunger < 100, 'Survival hunger falls with time');
assert(ladderMark(survival, sp) > before, 'Survival gains XP with time');
assert.equal(rp.nutrition, 0, 'Rise growth does not tick with time');
const heal = new Game('rise', setup, 47);
heal.skipHatch();
const hp = heal.players[0];
hp.spawnProtect = 1000;
const advance = (burst = 0) => {
  hp.sinceHit = 10;
  const old = hp.hp;
  heal.step(1 / 60, new Map([[0, { ...emptyInput(), burst }]]));
  heal.events.length = 0;
  return hp.hp - old;
};
hp.hp = hp.hpMax * 0.5;
heal.world.floraHash.clear();
const ordinary = advance();
assert(ordinary > 0, 'Health recovers at rest');
assert.equal(advance(1), 0, 'Sprinting pauses recovery');
const plant = { pos: { ...hp.pos }, kind: 'vauxia' as const, scale: 1, sy: 1, rot: 0, shade: 1, H: lengthOf(hp), R: 2, maxB: 0, bx: 0, bz: 0, bvx: 0, bvz: 0, active: true };
heal.world.flora.push(plant);
heal.world.floraHash.insert(plant);
hp.hp = hp.hpMax * 0.5;
const sheltered = advance();
assert(Math.abs(sheltered / ordinary - 2) < 0.1, 'A nearby seafloor plant doubles recovery');
const food = survival.actors.find((a) => a !== sp && a.controller !== 'player' && a.controller !== 'giant')!;
assert(food, 'A creature is available to eat');
const sim = survival as unknown as { canEat(a: typeof sp, food: typeof food): boolean; gainNutrition(a: typeof sp, food: typeof food, amount: number): void; respawn(a: typeof sp): void; nutritionValue(a: typeof sp, food: typeof food): number };
sp.hunger = 100;
assert(!sim.canEat(sp, food), 'A full player cannot eat');
sp.hunger = 0;
assert(sim.canEat(sp, food), 'An empty player can eat');
const xp = ladderMark(survival, sp);
sim.gainNutrition(sp, food, sim.nutritionValue(sp, food));
assert(sp.hunger > 0, 'Eating refills hunger');
assert.equal(ladderMark(survival, sp), xp, 'Eating does not award Survival growth');
placeOnLadder(survival, sp, 3.8);
sim.respawn(sp);
assert.equal(Math.floor(ladderMark(survival, sp)), 2, 'Survival death drops exactly one tier');
console.log('PASS Survival hunger, timed XP, eating, mode isolation, and tier loss');
