/** Verify the material repair retains the original albedo and all non-material data. */
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{execFileSync}from'node:child_process';
import {NodeIO}from'@gltf-transform/core';import{ALL_EXTENSIONS}from'@gltf-transform/extensions';import{MeshoptDecoder}from'meshoptimizer';await MeshoptDecoder.ready;
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.decoder':MeshoptDecoder});const sha=x=>crypto.createHash('sha256').update(x).digest('hex');const data=a=>Array.from(a.getArray());
const sourcePath='tools/triassic/creatures/nothosaurus/tripo-raw/nothosaurus.raw.glb';
const source=await io.read(sourcePath),sourceAlbedo=source.getRoot().listMaterials()[0].getBaseColorTexture();const report={sourceSha256:sha(fs.readFileSync(sourcePath)),sourceAlbedoSha256:sha(sourceAlbedo.getImage()),models:[]};
function topology(p){const a=p.getIndices().getArray(),rows=[];for(let i=0;i<a.length;i+=3){const tri=[a[i],a[i+1],a[i+2]],k=tri.indexOf(Math.min(...tri));rows.push([tri[k],tri[(k+1)%3],tri[(k+2)%3]].join(','));}return rows.sort();}
function structure(d){return{skins:d.getRoot().listSkins().map(s=>({joints:s.listJoints().map(n=>[n.getName(),n.getParentNode()?.getName(),n.getTranslation(),n.getRotation(),n.getScale()]),bind:data(s.getInverseBindMatrices())})),meshes:d.getRoot().listMeshes().map(m=>m.listPrimitives().map(p=>({orientedTriangles:topology(p),attributes:p.listSemantics().filter(s=>s!=='COLOR_0').sort().map(s=>[s,data(p.getAttribute(s))])})))};}
function clipHashes(d){return Object.fromEntries(d.getRoot().listAnimations().map(a=>[a.getName(),sha(Buffer.from(JSON.stringify(a.listChannels().map(c=>[c.getTargetNode().getName(),c.getTargetPath(),data(c.getSampler().getInput()),data(c.getSampler().getOutput())]))))]));}
function tailChannels(d,name){const a=d.getRoot().listAnimations().find(a=>a.getName()===name);return a.listChannels().filter(c=>c.getTargetNode().getName().startsWith('tail_')).map(c=>[c.getTargetNode().getName(),c.getTargetPath(),data(c.getSampler().getInput()),data(c.getSampler().getOutput())]);}
function assertTailClose(current,baseline){assert.equal(current.length,baseline.length);for(let i=0;i<current.length;i++){assert.equal(current[i][0],baseline[i][0]);assert.equal(current[i][1],baseline[i][1]);for(const k of[2,3]){assert.equal(current[i][k].length,baseline[i][k].length);for(let j=0;j<current[i][k].length;j++)assert(Math.abs(current[i][k][j]-baseline[i][k][j])<1e-6);}}}
for(const suffix of ['', '.puppet','.lod1']){
 const file='public/assets/triassic/creatures/nothosaurus'+suffix+'.glb',d=await io.read(file);const body=d.getRoot().listMaterials().find(m=>/Nothosaurus (body pigmentation|puppet body)/.test(m.getName()));const row={suffix,sha256:sha(fs.readFileSync(file)),baseColorTexture:body.getBaseColorTexture()?.getName()??null,normalScale:body.getNormalScale(),roughness:body.getRoughnessFactor(),metallic:body.getMetallicFactor()};
 assert.equal(body.getMetallicFactor(),0);assert.equal(body.getMetallicRoughnessTexture(),null);
 if(!suffix){assert(body.getBaseColorTexture());assert.equal(sha(body.getBaseColorTexture().getImage()),report.sourceAlbedoSha256);assert(Math.abs(body.getNormalScale()-.15)<1e-6);assert(Math.abs(body.getRoughnessFactor()-.7)<1e-6);let count=0;for(const m of d.getRoot().listMeshes())for(const p of m.listPrimitives())if(p.getMaterial()===body){const a=p.getAttribute('COLOR_0');assert(a);const white=a.getNormalized()?(a.getComponentType()===5123?65535:255):1;for(const n of a.getArray())assert.equal(n,white);count+=a.getCount();}row.whiteColorVertices=count;row.sourceAlbedoPreservedExactly=true;}
 const baseline=execFileSync('git',['show',`HEAD:${file}`],{maxBuffer:16*1024*1024}),old=await io.readBinary(baseline);assert.deepEqual(structure(d),structure(old));
 const currentClips=clipHashes(d),oldClips=clipHashes(old),changed=Object.keys(currentClips).filter(name=>currentClips[name]!==oldClips[name]).sort();assert.deepEqual(changed,['Sprint','Swim']);
 for(const name of changed)assertTailClose(tailChannels(d,name),tailChannels(old,name));
 row.geometryNormalsUvWeightsRigUnchanged=true;row.intentionallyChangedClips=changed;row.tailChannelsUnchanged=true;row.baselineSha256=sha(baseline);
 report.models.push(row);
}
// Original source UV corners vs unchanged exported skin vertices, after the exact axis/scale transform.
const full=await io.read('public/assets/triassic/creatures/nothosaurus.glb'),dict=new Map(),key=p=>p.map(x=>x.toFixed(4)).join(',');
for(const m of source.getRoot().listMeshes())for(const p of m.listPrimitives()){const v=p.getAttribute('POSITION'),uv=p.getAttribute('TEXCOORD_0');for(let i=0;i<v.getCount();i++){const a=v.getElement(i,[]),b=[-5*a[2],5*a[1],5*a[0]],k=key(b);if(!dict.has(k))dict.set(k,[]);dict.get(k).push({pos:b,uv:uv.getElement(i,[])});}}
let matched=0,cut=0,bad=0,worst=0;
for(const m of full.getRoot().listMeshes())for(const p of m.listPrimitives()){if(!p.getMaterial().getName().startsWith('Nothosaurus body'))continue;const v=p.getAttribute('POSITION'),uv=p.getAttribute('TEXCOORD_0');for(let i=0;i<v.getCount();i++){const pos=v.getElement(i,[]),values=uv.getElement(i,[]),a=(dict.get(key(pos))??[]).filter(x=>Math.hypot(...x.pos.map((n,j)=>n-pos[j]))<2e-6);if(!a.length){cut++;continue;}matched++;const delta=Math.min(...a.map(x=>Math.max(...x.uv.map((n,j)=>Math.abs(n-values[j])))));worst=Math.max(worst,delta);if(delta>1e-5)bad++;}}
report.sourceUvComparison={matchedOriginalSurfaceVertices:matched,newCutOrRoundingBoundaryVertices:cut,above1eMinus5Tolerance:bad,maximumUvDifference:worst,maximumDifferenceIn2kTexels:worst*2048};assert(worst<1/2048);
fs.writeFileSync('tools/triassic/creatures/nothosaurus/material-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
